<?php
/*
Les textes doivent comporter :
— les apostrophes typographique (’ et non '),
— les ligatures æ, Æ, œ et Œ,
— les espaces insécables là ou ils sont nécessaire,
— les majuscules accentuées.
*/ 

$textes[0]["source"] = "https://fr.wikisource.org/wiki/Traité_de_la_mécanique";
$textes[0]["txt"] = "L’invention de tous ces engins n’est fondée que sur un seul principe, qui est que la même force qui peut lever un poids, par exemple, de cent livres à la hauteur de deux pieds, en peut aussi lever un de deux cents livres à la hauteur d’un pied, ou un de quatre cents à la hauteur d’un demi-pied, et ainsi des autres, si tant est qu'elle lui soit appliquée. Et ce principe ne peut manquer d’être reçu si on considère que l’effet doit être toujours proportionné à l’action qui est nécessaire pour le produire ; de façon que, s’il est nécessaire d’employer l’action par laquelle on peut lever un poids de cent livres à la hauteur de deux pieds pour en lever un à la hauteur d’un pied seulement, celui-ci doit peser deux cents livres : car c’est le même de lever cent livres à la hauteur d’un pied, et derechef encore cent à la hauteur d’un pied, que d’en lever deux cents à la hauteur d’un pied, et le même aussi que d’en lever cent à la hauteur de deux pieds. Or les engins qui servent à faire cette application d’une force qui agit…";


$textes[1]["source"] = "https://fr.wikisource.org/wiki/Mémoires_sur_l’électromagnétisme_et_l’électrodynamique/Premier_mémoire";
$textes[1]["txt"] = "Suivant le sens dans lequel on fait passer le courant dans une telle spirale, elle est en effet fortement attirée ou repoussée par le pôle d’un aimant qu’on lui présente de manière que la direction de son axe soit perpendiculaire au plan de la spirale, selon que les courants électriques de la spirale et du pôle de l’aimant sont dans le même sens ou en sens contraire. En remplaçant l’aimant par une autre spirale, dont le courant soit dans le même sens que le sien, on a les mêmes attractions et répulsions ; c’est ainsi que j’ai découvert que deux courants électriques s’attirent quand ils ont lieu dans le même sens, et se repoussent dans le cas contraire. En remplaçant ensuite, dans l’expérience de l’action mutuelle d’un des pôles d’un aimant et d’un courant dans un fil métallique plié en spirale, cette spirale par un autre aimant, on a encore les mêmes effets, soit en attraction, soit en répulsion, conformément à la loi des phénomènes connus de l’aimant ; il est évident d’ailleurs que toutes les circonstances…";


$textes[2]["source"] = "https://fr.wikisource.org/wiki/Qu’est_ce_que_la_propriété_%3F";
$textes[2]["txt"] = "Si j’avais à répondre à la question suivante : Qu’est-ce que l’esclavage ? et que d’un seul mot je répondisse : c’est l’assassinat, ma pensée serait d’abord comprise. Je n’aurais pas besoin d’un long discours pour montrer que le pouvoir d’ôter à l’homme la pensée, la volonté, la personnalité, est un pouvoir de vie et de mort, et que faire un homme esclave, c’est l’assassinat. Pourquoi donc à cette autre demande : Qu’est-ce que la propriété ? ne puis-je répondre de même : c’est le vol, sans avoir la certitude de n’être pas entendu, bien que cette seconde proposition ne soit que la première transformée ? J’entreprends de discuter le principe même de notre gouvernement et de nos institutions, la propriété ; je suis dans mon droit : je puis me tromper dans la conclusion qui ressortira de mes recherches ; je suis dans mon droit : il me plaît de mettre la dernière pensée de mon livre au commencement ; je suis toujours dans mon droit. Tel auteur enseigne que la propriété est un droit civil, né de l’occupation et…";


$textes[3]["source"] = "http://www.lemonde.fr/pixels/article/2016/01/19/avec-le-clavier-azerty-il-est-presque-impossible-d-ecrire-en-francais-correctement_4849787_4408996.html";
$textes[3]["txt"] = "Toutes les Lætitia le savent : taper le fameux « e dans l’a » sur un clavier d’ordinateur n’est pas une mince affaire. Et il se trouve que ce genre de difficulté, propre à la langue française, agace aussi le ministère de la culture et de la communication. Il est « presque impossible d’écrire en français correctement avec un clavier commercialisé en France », peut-on lire dans un rapport de la Délégation générale à la langue française et aux langues de France publié vendredi 15 janvier sur le site du ministère. Ce dernier préconise la création d’un nouveau modèle de clavier pour répondre à cette problématique. Parmi les autres difficultés récurrentes rencontrées par les Français avec leurs claviers, les caractères accentués en majuscule, les « c » cédille majuscule ou encore les doubles chevrons, aussi connus sous le nom de « guillemets français », précise le rapport. Il souligne aussi la diversité des claviers disponibles sur le marché français, qui ne placent pas au même endroit des touches aussi utiles que « @ » ou « € »…";


$textes[4]["source"] = "https://fr.wikisource.org/wiki/À_se_tordre/Un_philosophe";
$textes[4]["txt"] = "Je m’étais pris d’une profonde sympathie pour ce grand flemmard de gabelou que me semblait l’image même de la douane, non pas de la douane tracassière des frontières terriennes, mais de la bonne douane flâneuse et contemplative des falaises et des grèves. Son nom était Pascal ; or, il aurait dû s’appeler Baptiste, tant il apportait de douce quiétude à accomplir tous les actes de sa vie. Et c’était plaisir de le voir, les mains derrière le dos, traîner lentement ses trois heures de faction sur les quais, de préférence ceux où ne s’amarraient que des barques hors d’usage et des yachts désarmés. Aussitôt son service terminé, vite Pascal abandonnait son pantalon bleu et sa tunique verte pour enfiler une cotte de toile et une longue blouse à laquelle des coups de soleil sans nombre et des averses diluviennes (peut-être même antédiluviennes) avaient donné ce ton spécial qu’on ne trouve que sur le dos des pêcheurs à la ligne. Car Pascal pêchait à la ligne, comme feu monseigneur le prince de Ligne lui-même. Pas un homme comme lui pour connaître les bons coins dans les…";


$textes[5]["source"] = "https://fr.wikisource.org/wiki/À_se_tordre/Ferdinand";
$textes[5]["txt"] = "Les bêtes ont-elles une âme ? Pourquoi n’en auraient-elles pas ? J’ai rencontré, dans la vie, une quantité considérable d’hommes, dont quelques femmes, bêtes comme des oies, et plusieurs animaux pas beaucoup plus idiots que bien des électeurs. Et même – je ne dis pas que le cas soit très fréquent – j’ai personnellement connu un canard qui avait du génie. Ce canard, nommé Ferdinand, en l’honneur du grand Français, était né dans la cour de mon parrain, le marquis de Belveau, président du comité d’organisation de la Société générale d’affichage dans les tunnels. C’est dans la propriété de mon parrain que je passais toutes mes vacances, mes parents exerçant une industrie insalubre dans un milieu confiné. (Mes parents – j’aime mieux le dire tout de suite, pour qu’on ne les accuse pas d’indifférence à mon égard – avaient établi une raffinerie de phosphore dans un appartement du cinquième étage, rue des Blancs-Manteaux, composé d’une chambre, d’une cuisine et d’un petit cabinet de débarras, servant de salon.) Un véritable éden, la propriété de mon parrain ! Mais c’est…";


$textes[6]["source"] = "https://fr.wikisource.org/wiki/À_se_tordre/Mœurs_de_ce_temps-ci";
$textes[6]["txt"] = "À la fois très travailleur et très bohème, il partage son temps entre l’atelier et la brasserie, entre son vaste atelier du boulevard Clichy et les gais cabarets de Montmartre. Aussi sa mondanité est-elle restée des plus embryonnaires. Dernièrement, il a eu un portrait à faire, le portrait d’une dame, d’une bien grande dame, une haute baronne de la finance doublée d’une Parisienne exquise. Et il s’en est admirablement tiré. Elle est venue sur la toile comme elle est dans la vie, c’est-à-dire charmante et savoureuse avec ce je ne sais quoi d’éperdu. Au prochain Salon, après avoir consulté un décevant livret, chacun murmurera, un peu troublé : « Je voudrais bien savoir quelle est cette baronne. » Et elle a été si contente de son portrait qu’elle a donné en l’honneur de son peintre un dîner, un grand dîner. Au commencement du repas, il a bien été un peu gêné dans sa redingote inaccoutumée, mais il s’est remis peu à peu. Au dessert, s’il avait eu sa pipe, sa bonne pipe, il aurait été tout fait heureux. On a servi le café dans la serre, une merveille de serre où l’industrie…";


$textes[7]["source"] = "https://fr.wikisource.org/wiki/À_se_tordre/Cruelle_Énigme";
$textes[7]["txt"] = "Chaque soir, quand j’ai manqué le dernier train pour Maisons-Laffitte (et Dieu sait si cette aventure m’arrive plus souvent qu’à mon tour), je vais dormir en un pied-à-terre que j’ai à Paris. C’est un logis humble, paisible, honnête, comme le logis du petit garçon auquel Napoléon III, alors simple président de la République, avait logé trois balles dans la tête pour monter sur le trône. Seulement, il n’y a pas de rameau bénit sur un portrait, et pas de vieille grand-mère qui pleure. Heureusement ! Mon pied-à-terre, j’aime mieux vous le dire tout de suite, est une simple chambre portant le numéro 80 et sise en l’hôtel des Trois Hémisphères, rue des Victimes. Très propre et parfaitement tenu, cet établissement se recommande aux personnes seules, aux familles de passage à Paris, ou à celles qui, y résidant, sont dénuées de meubles. Sous un aspect grognon et rébarbatif, le patron, M. Stéphany, cache un cœur d’or. La patronne est la plus accorte hôtelière du royaume et la plus joyeuse. Et puis, il y a souvent, dans le bureau, une dame qui s’appelle Marie et qui est…";


$textes[8]["source"] = "https://fr.wikisource.org/wiki/À_se_tordre/Boisflambard";
$textes[8]["txt"] = "La dernière fois que j’avais rencontré Boisflambard, c’était un matin, de très bonne heure (je ne me souviens plus quelle mouche m’avait piqué de me lever si tôt), au coin du boulevard Saint-Michel et de la rue Racine. Mon pauvre Boisflambard, quantum mutatus ! À cette époque-là, le jeune Boisflambard résumait toutes les élégances du Quartier latin. Joli garçon, bien tourné, Maurice Boisflambard s’appliquait à être l’homme le mieux « mis » de toute la rive gauche. Le vernis de ses bottines ne trouvait de concurrence sérieuse que dans le luisant de ses chapeaux, et si on ne se lassait pas d’admirer ses cravates, on avait, depuis longtemps, renoncé à en savoir le nombre. De même pour ses gilets. Que faisait Boisflambard au Quartier latin ? Voilà ce que personne n’aurait pu dire exactement. Étudiant ? En quoi aurait-il été étudiant et à quel moment de la journée aurait-il étudié ? Quels cours, quelles cliniques aurait-il suivis ? Car Boisflambard ne fréquentait, dans la journée, que les brasseries de dames ; le soir, que le bal Bullier ou un petit concert énormément…";


$textes[9]["source"] = "https://www.revue-ballast.fr/quelle-revolution-au-rojava/";
$textes[9]["txt"] = "Qu’est-ce qu’une révolution ? Une montagne de contradictions. Les candides se trouvent bientôt déçus, toujours, puisque la réalité froisse leurs rêves les plus ambitieux ; les puristes crachent leur bile, toujours, puisqu’ils ne voient que le verre à moitié vide et feraient, bien sûr, tout mieux que tout le monde s’ils étaient aux manettes. L’Histoire n’a plus à le prouver : toute révolution comporte son lot d’impairs, de reculades, de compromissions, voire d’exactions — il ne s’agit pas de s’en contenter, encore moins de s’en laver les mains, seulement de penser et d’agir politiquement, c’est-à-dire comme on peut, cahin-caha, les pieds dans cette matière aussi instable qu’est la Terre des hommes. Le Rojava, estime Noam Chomsky, tente, dans la limite des conditions fixées par la guerre en Syrie, d’instaurer une « société assez décente » — raison pour laquelle, poursuit l’analyste américain, ils « méritent assurément soutien ». Nous traduisons cet entretien de l’anglais : un anarchiste occidental a intégré les Unités de Protection du Peuple (YPG) afin de prendre…";


$textes[10]["source"] = "https://www.revue-ballast.fr/le-municipalisme-libertaire-quest-ce-donc/";
$textes[10]["txt"] = "On reproche régulièrement aux partageux de critiquer sans proposer. Le municipalisme libertaire (ou communalisme), né au début des années 1970 sous la plume de l’écologiste états-unien Murray Bookchin, constitue pourtant l’un des projets de société les plus structurés au sein du mouvement anticapitaliste. Mais un projet méconnu. Fort des trois échecs du siècle dernier (le communisme mondial, l’anarchisme local et le réformisme parlementaire), le municipalisme libertaire propose, par un processus révolutionnaire social et écologique, de « remplacer l’État, l’urbanisation, la hiérarchie et le capitalisme par des institutions de démocratie directe et de coopération ». Ce fut l’œuvre de Bookchin ; ce fut même, confia-t-il, le but de son existence et sa seule « raison d’espérer ». On aurait raison de se méfier des théories radieuses et des horizons clés en main ; on aurait tort de les railler à l’ère du dérèglement climatique, de la sixième extinction de masse, de l’abstention galopante, de la poussée nationaliste, de l’épuisement prochain des réserves de pétrole et…";


$textes[11]["source"] = "https://www.revue-ballast.fr/le-salaire-a-vie-quest-ce-donc/";
$textes[11]["txt"] = "De manière simplifiée, le PIB se compose de trois éléments : le salaire, le profit et les cotisations sociales. Loin d’être des charges, ces dernières sont une forme de salaire continué, socialisé. La rémunération des soignants, considérés comme utiles mais toujours trop coûteux, pourrait être vue non plus comme une ponction sur la valeur ajoutée mais comme la reconnaissance de leur travail : s’ils sont payés, c’est parce que l’activité qu’ils exercent fait d’eux des producteurs de valeur économique. De la même façon, les cotisations payent les retraités, les chômeurs et les parents, qui élèvent leurs enfants avec les allocations : elles attribuent une valeur aux activités des ces « improductifs » — car hors du cadre de l’emploi. Octroyer un salaire à vie pour tous, de manière inconditionnelle, serait le prolongement de cette logique déjà en partie à l’œuvre. Comment le financer ? En attribuant l’ensemble du PIB à la cotisation. Les entreprises cotiseraient à plusieurs caisses : une pour les salaires, une dédiée à l’investissement, une qui financerait des services…";


$textes[12]["source"] = "https://www.revue-ballast.fr/commune-caste-gustave-lefrancais/";
$textes[12]["txt"] = "La Commune, c’est le parti de ceux qui avaient d’abord protesté contre la guerre en juillet 1870, mais qui, voyant l’honneur et l’intégrité de la France compromises par votre lâcheté sous l’Empire, ont tenté l’impossible pour que l’envahisseur fût repoussé hors des frontières, alors que vous ne songiez qu’à lui livrer Paris pour reprendre au plus vite votre existence de tripoteurs et de jouisseurs. La Commune, pendant six mois, a mis en échec votre œuvre de trahison. Jamais, jamais vous ne le lui pardonnerez. La Commune a démontré que le prolétariat était préparé à s’administrer lui-même et pouvait se passer de vous, alors que vous vous prétendiez seuls capables de « mener les affaires ». La réorganisation immédiate des services publics, que vous aviez abandonnés, en est la preuve évidente. Jamais vous ne le lui pardonnerez. La Commune a tenté de substituer l’action directe et le contrôle incessant des citoyens à vos gouvernements, tous basés sur la « raison d’État », derrière laquelle s’abritent vos pilleries et vos infamies gouvernementales de toutes sortes.…";


$textes[13]["source"] = "https://www.revue-ballast.fr/journaux-nen-lisez-plus/";
$textes[13]["txt"] = "J’étais dans le cabinet des métaphores, la loupe à l’œil, à regarder dans le mécanisme compliqué du style. Le style c’était une invention de l’âme pour distraire l’esthète que j’étais. Je trouvais du style à tout et préfigurais même une télévision odorante, une télévision à diriger l’économie olfactive. Nous y arrivons, patience ! Le style c’est cette partie du beau qui s’analyse, dans le repos, quand le spectacle flanche. C’est un arrêt dans la culture, pour mieux goûter. Le style c’est cette dame qui descendait l’autre matin les Champs-Elysées, plantée sur des aiguilles et dont le balancement se ressentait de cette position perchée et voulue telle. C’est ainsi que déambulent les hommes efféminés, me disais-je. Le style c’était la « femme », bateau à voile dérivant parmi la foule, tout envergué de chair gonflée et de prescience, l’œil en vigie à scruter le pirate. Le faux, la basse imitation gisait dans mon for intérieur quand j’échangeais les sexes. Le style meurt d’une intention frauduleuse. Le style c’est une prison dans un champ libre. C’est le bâillon du…";


$textes[14]["source"] = "https://www.revue-ballast.fr/jean-paul-jouary-de-tout-temps-les-democrates-ont-refuse-le-suffrage-universel/";
$textes[14]["txt"] = "On voit bien que cette démocratie « représentative » ne fonctionne plus du tout. Si, aussitôt élus, les « représentants » peuvent diriger en contradiction avec les aspirations d’une sensible majorité des citoyens, c’est qu’ils ne les « représentent » pas. D’ailleurs, que signifie « représenter » ? Re-présenter, c’est recréer une présence lorsqu’elle est impossible. Ainsi, un représentant de commerce ou un ambassadeur re-présentent leur entreprise ou leur pays. Qu’ils prennent la moindre initiative contre ce qu’ils sont censés représenter, et on leur fait payer cette prétention au pouvoir en les chassant de leur fonction. On ne re-présente au sens de « décider à la place de » que dans deux cas : lorsqu’un enfant est trop jeune, alors les parents le représentent et décident à sa place, et lorsqu’une personne est malade mentale, alors des tuteurs font de même. Dans ce que l’on appelle la « démocratie représentative », si les élus prétendent « représenter » le peuple sans lui obéir par voie référendaire mais en prétendant décider à sa place pendant une période donnée,…";


$textes[15]["source"] = "http://menace-theoriste.fr/apophenie-illusions-de-perception/";
$textes[15]["txt"] = "Nous sommes des unités informativores. Nous ingurgitons constamment des stimuli que nous analysons pour comprendre le monde. Tous les animaux fonctionnent ainsi, mais nous avons atteint un niveau de raffinement extrême grâce auquel notre espèce réussit des prouesses techniques, artistiques et scientifiques. Nous sommes capables d’identifier les informations pertinentes au milieu du bruit des stimulations tous azimut de notre environnement. Pensons à l’effet cocktail : au milieu d’un brouhaha informe, nous avons la capacité d’isoler un flux verbal, de le faire ressortir du bruit ambiant afin d’en comprendre le sens. Et dans le même temps, une partie de notre attention reste disponible pour un stimulus externe. Par exemple, nous percevons si notre nom est prononcé, ou si une voix familière se rapproche. Cette compétence de reconnaissance de forme est le fondement de la grille de lecture qu’utilise notre cerveau pour se représenter le monde. Nous sommes tellement forts dans cette tâche, qu’il nous arrive de commettre des excès de zèle. Pour s’en convaincre, on peut…";


$textes[16]["source"] = "http://menace-theoriste.fr/zetetique/";
$textes[16]["txt"] = "La zététique consiste à questionner les raisons pour lesquelles nous pensons que quelque chose est vrai. Malgré son nom un peu exotique, la zététique n’est rien d’autre que la méthode scientifique (hypothético-déductive) appliquée à toutes sortes de questions qui peuvent nous sembler a priori étrangères à la science. Pour illustrer cela, prenons un exemple d‘illusion statistique. Jamais au cours de l’histoire les cancers, Parkinson et Alzheimer n’ont été aussi fréquents. C’est un fait brut. D’aucuns en concluent que notre environnement ou notre nourriture représentent un danger : autrefois les gens vivaient plus sainement, et il nous faudrait revenir à ces modes de vie ancestraux. Cette interprétation n’est en réalité étayée par rien et sa vraisemblance disparaît si on ajoute une simple donnée : l’espérance de vie en bonne santé n’a jamais été aussi grande. Par conséquent la fréquence des cancers, Parkinson et Alzheimer s’explique par le vieillissement de la population. L’importance relative des maladies dégénératives est paradoxalement la preuve que la santé…";


$textes[17]["source"] = "http://menace-theoriste.fr/le-reflexe-correcteur/";
$textes[17]["txt"] = "Qu’y a-t-il de plus stérile, dans un échange sur le net, qu’une réponse toute entière concentrée sur l’orthographe de son interlocuteur ? Vous savez bien, en lisant ce genre d’échange, que celui qui s’adonne à la correction de l’autre au lieu de répondre sur le fond échoue totalement, irrémédiablement à le convaincre. Avoir raison sur la bonne manière d’épeler un mot n’est pas un argument, mais peut devenir une forme d’intimidation par l’orthographe. Volontairement ou involontairement, le correcteur induit chez l’autre le sentiment d’être rabaissé, méprisé. Bien sûr, nous sommes tous responsables de nos propres émotions, mais les émotions des autres sont toujours dans l’équation, et il parait peu raisonnable de vouloir purement et simplement les nier. Malheureusement, nous éprouvons facilement l’envie d’aller sur ce terrain, c’est notre réflexe correcteur. Ce n’est pas toujours une mauvaise chose ; il est naturel de vouloir redresser ce qui est de travers (dans le sens où notre faculté de raisonnement sert un peu à ça). L’intention peut être bonne, même quand…";


$textes[18]["source"] = "http://menace-theoriste.fr/la-violence-epistemique/";
$textes[18]["txt"] = "Le discours sceptique est irritant. Tel un solvant universel, il s’attaque aux objets de croyances et même aux récipients qui veulent le contenir (les paradigmes). Mesdames et messieurs les zététiques, nous manipulons un produit dangereux, irritant. Il convient donc de ne pas en badigeonner tout le monde autour de nous à la légère, à la volée, à la hussarde. Dans le cas des croyances religieuses en particulier, l’adhésion à la croyance s’accompagne d’un « coût ». Il faut respecter certains interdits, suivre des rites, obéir à des obligations, souvent donner de l’argent. Cet engagement fait partie de ce qui rend la croyance importante : personne n’aime investir pour rien. Dès lors la simple présence de quelqu’un qui rejette cette croyance est source de souffrance, car l’impie ne s’acquitte pas des sacrifices consentis par le croyant. Cette souffrance est une forme de dissonance cognitive. Et cette souffrance, puisqu’elle a pour cause l’existence de cette personne qui ne croit pas, c’est donc bien le non croyant qui fait souffrir le croyant, et il peut estimer…";


$textes[19]["source"] = "http://menace-theoriste.fr/portrait-robot-de-lignorance/";
$textes[19]["txt"] = "L’ignorance n’est pas un terrain vierge, c’est une forêt d’idées préconçues, de concepts mal compris, des marais de préjugés, des bosquets de certitudes erronées… Bref, c’est un cauchemar. Un peu d’éducation ne règle malheureusement pas le problème aussi facilement qu’on aurait tendance à le croire. Recevoir un peu d’éducation revient à élaguer un peu toute cette ignorance pour y planter des connaissances, ce qui ne permet pas d’éliminer toutes les mauvaises herbes ; la personne un peu éduquée reste pleine d’hypothèses, de croyances, d’intuitions, de métaphores, de concepts erronés qu’elle n’a pas vérifiés, qu’elle n’a pas questionnés, et qui contribuent à sa vision du monde. L’ignorant ou l’incompétent n’est pas une personne totalement non-informée, c’est une personne mal informée, ce qui est pire, car bien souvent elle croit qu’elle sait, ou en tout les cas elle ignore à quel point elle est ignorante. Ce risque a conduit le chercheur suédois Nils Petter Gregersen à recommander que les gens ne suivent surtout pas de stage de conduite en conditions extrêmes.…";


$textes[20]["source"] = "https://www.monde-diplomatique.fr/2009/05/LEPAGE/17113";
$textes[20]["txt"] = "En France, quand on prononce le mot « culture », chacun comprend « art » et plus précisément « art contemporain ». Le mot Culture, avec son singulier et sa majuscule, suscite une religiosité appuyée sur ce nouveau sacré, l’art, essence supérieure incarnée par quelques individus eux-mêmes touchés par une grâce — les « vrais » artistes. La population, elle, est invitée à contempler le mystère. Entamée dès les années 1960 sous l’égide du ministère des affaires culturelles, la réduction de la culture à l’art représente une catastrophe intellectuelle pour tout homme ou toute femme de progrès. Si « culture » ne veut plus dire qu’« art », alors ni l’action syndicale, ni les luttes des minorités, ni le féminisme, ni l’histoire, ni les métiers, ni la paysannerie, ni l’explication économique, etc., ne font plus partie de la culture. Entre cette dernière et la politique s’instaure un rapport d’exclusion. Et la gauche a un problème. Tel n’a pas toujours été le cas. Il fut un temps — pas si éloigné — où un petit groupe de militants nichés au cœur des institutions françaises…";


$textes[21]["source"] = "http://menace-theoriste.fr/eponymie-et-effet-matthieu/";
$textes[21]["txt"] = "En substance, l’effet Matthieu produit la chose suivante : un nom connu agrégera sur lui les mérites portant sur des travaux auxquels auront participé des chercheurs moins renommés… et dont la renommée ne pourra s’accroître puisque le mérite de leurs travaux leur est ôté. Il s’agit d’un phénomène « naturel » en ce sens que la communauté scientifique n’a jamais explicitement pris la décision de se comporter ainsi ; c’est le résultat de comportements individuels à l’échelle desquels on ne peut pas soupçonner l’émergence d’un effet important sur l’ensemble de la communauté. L’effet Matthieu est valable pour les institutions. Une étude publiée par une université ou un laboratoire très reconnu sera beaucoup plus citée qu’une étude de même qualité provenant d’une source moins prestigieuse. Comment cela est-il possible ? Une production intellectuelle provenant d’un excellent scientifique d’une illustre institution envoie plus de stimuli au lectorat que la même contribution signée d’un nom inconnu. Elle sera lue davantage, provoquera plus de réactions, et in fine pourra…";


$textes[22]["source"] = "https://www.revue-ballast.fr/alain-damasio-1/";
$textes[22]["txt"] = "Il y a une chose essentielle qui différencie l’art de la propagande. La propagande, comme disait Foucault, c’est l’art de « conduire des conduites », de créer quelque chose dans un registre argumentatif afin d’amener les gens à adopter certains comportements. Il y a une vraie volonté de manipuler la liberté des personnes, de la canaliser vers des points considérés comme relevant de la vérité. La grande différence et la grande chance, pour nous, artistes, c’est que nous sommes des « ouvreurs » : on ouvre le crâne des gens. Ce qui m’intéresse, c’est d’arriver à ce point où un déclic se fait, où les gens, simplement, ouvrent les yeux, les oreilles et parviennent à quelque chose d’autre. L’art doit permettre le décollement de la norme subie au quotidien. Il t’ouvre sur l’émotion, sur la perception, mais ne les ferme pas. La différence vient aussi du registre. Entre un registre poétique et un registre argumentatif, il y a une énorme différence. Toute la propagande relève de l’argumentatif : tu accumules des arguments qui te conduisent à une « vérité », tu réduis le…";


$textes[23]["source"] = "https://www.monde-diplomatique.fr/2017/06/BOELAERT/57596";
$textes[23]["txt"] = "En 2013, une députée socialiste de Gironde accusait certains de ses jeunes collègues d’être déconnectés de la « vraie vie » parce qu’ils n’auraient jamais vécu que dans le « tunnel de la politique ». Plus récemment, un pur produit de l’élite française nommé Emmanuel Macron déclarait : « Je ne fais pas partie de cette caste politique et je m’en félicite. Nos concitoyens sont las de cette caste » (SudOuest.fr, 9 mai 2016). Il réclamait l’émergence de « nouveaux visages » et érigeait « l’immaturité et l’inexpérience » en argument de campagne. La critique de la professionnalisation de la politique est populaire ; si populaire qu’elle peut même ouvrir le chemin de l’Élysée. Ces trajectoires tant décriées n’apparaissent pas d’emblée dans les statistiques. Conscients du stigmate qu’elles impliquent, les élus font tout pour s’en démarquer. On ne trouve ainsi aucun « professionnel de la politique » dans leurs fiches biographiques au Parlement. Ils mettront en avant toute activité autre, même de courte durée, même remontant à plusieurs décennies. Interrogés, ils rejettent…";


$textes[24]["source"] = "https://blog.mondediplo.net/le-complotiste-de-l-elysee";
$textes[24]["txt"] = "En général, le spectacle d’une déchéance n’est pas beau à voir, à plus forte raison quand elle est si précoce. Mais disons les choses : ici, c’est franchement drôle. Un peu inquiétant, sans doute (en fait beaucoup), mais drôle. En fait c’est surtout drôle d’imaginer les mâchoires décrochées des chasseurs de complotistes. Parce que Macron en roue libre dans la russosphère, les « gilets jaunes » pilotés depuis le Kremlin, pour n’importe qui, c’est à mourir de rire, mais pour eux, c’est Ganelon, Trafalgar et Blücher réunis. Normalement, on était d’accord : le complotisme, c’était pour les « autres », les « affreux », ceux précisément qui ne croient pas en la raison libérale. Mais comment fait-on si c’est le héros, celui pour qui on a raconté tout ça, qui décompense et se met à courir en chemise de nuit dans les rues ? Ici, on rêverait de voir leurs têtes à tous : Jean-Michel Aphatie, Patrick Cohen, Nicolas Demorand, Léa Salamé, Ali Baddou, Sonia Devillers (la chasse au complotisme n’a pas de soldats plus typiques que les demi-habiles de France Inter), mais aussi…";


$textes[25]["source"] = "https://blog.mondediplo.net/en-guerre-pour-la-preemption-salariale";
$textes[25]["txt"] = "Mais le point de triomphe de l’ordre néolibéral désigne aussitôt son point de faiblesse. « Il n’y a pas d’alternative » n’est jamais qu’un énoncé conditionnel à l’état de ses structures. Faire autrement est impossible puisque la nécessité installée par les structures s’oppose à ce qu’on fasse autrement ? Très bien, nous savons maintenant où se situe l’enjeu : dans la reconstruction des structures. Voilà le discours manquant, celui qui laisse une chance de respirer à nouveau au sortir d’un film étouffant : le discours des structures comme objet de la politique. Car, elles, peuvent toujours être refaites – autrement. Ce « toujours », c’est le nom même de la politique. Dès lors qu’on s’élève au niveau des structures, il y a toujours une alternative. L’alternative peut entrer bien plus vite dans la réalité qu’on ne l’imagine, très soudainement même. En Argentine, pendant toutes les années 1990, le currency board impose une politique monétaire déflationniste, et pour qu’il ne vienne à l’idée de personne de « faire autrement », on l’a inscrit dans la Constitution (grande…";


$textes[26]["source"] = "https://blog.mondediplo.net/2018-03-12-Tarnac-justice-de-justice-ou-justice-d-Etat";
$textes[26]["txt"] = "Si seulement le monstre froid était froid… Mais même pas. Il a ses petits affects lui aussi. D’abord, bien sûr, ceux de la paranoïa en roue libre – mais elle lui est presque congénitale. Il faut en tout cas avoir atteint le dernier degré de la coupure d’avec tout, et presque d’avec la vie, pour se tenir, forcené, au délire des mouvements sociaux téléguidés par le leader caché depuis sa catacombe – comme souvent, c’est le schème de la séparation manipulatrice qui est projectivement prêté par les séparés-manipulateurs. Or il est certain que tout ce que l’État compte de paranoïaques tient avec certitude que, Julien Coupat ôté, les mouvements sont supprimés. Que la pensée complotiste soit le propre en tout premier lieu des hommes de pouvoir, c’est-à-dire des professionnels du complot (et par transitivité de tous leurs porte-coton), la chose n’a évidemment rien que de très logique. L’interprétation la plus charitable toutefois serait celle de l’hommage, mais inconscient bien sûr, que le vice rend à la vertu. Hommage par la croyance partagée, quoique dans un rageux…";


$textes[27]["source"] = "https://blog.mondediplo.net/2013-02-18-La-regulation-bancaire-au-pistolet-a-bouchon";
$textes[27]["txt"] = "Ce sera sans doute la perle de la crise. Karine Berger, députée socialiste, rapporteure du projet de loi dit de « séparation » et de « régulation » des activités bancaires, reprenant la parole en commission des finances après les exposés de MM. Chifflet, Oudéa et Bonnafé, respectivement président de la Fédération bancaire française, président de la Société Générale et directeur-général de BNP-Paribas : « Vos trois exposés laissent paraître que vous n’êtes pas réellement gênés par ce projet de loi ; j’en suis à la fois étonnée et ravie »… Qu’elle en fût uniquement étonnée n’aurait trahi qu’une charmante simplicité d’esprit. Qu’elle en soit au surplus ravie ne laisse plus le moindre doute quant au côté où elle se tient. Pour notre part, plus rien ne nous étonne dans les rapports du socialisme de gouvernement et de la finance — quant au ravissement, évidemment… « I am not dangerous », s’était empressé de préciser François Hollande à l’adresse de la City qu’il était venu rassurer après l’avoir nommée « l’ennemi sans visage », sans doute dans un moment d’égarement,…";


$textes[28]["source"] = "https://blog.mondediplo.net/2013-04-12-Le-balai-comme-la-moindre-des-choses";
$textes[28]["txt"] = "Seuls ceux qui portent sur la politique le regard scolastique des logiciens auront du mal à comprendre qu’on puisse dire d’un même événement — comme l’affaire Cahuzac — qu’il est à la fois secondaire et principal. Péripétie fait-diversière et crapoteuse, bien faite pour attraper le regard et le détourner des choses importantes (accord sur l’emploi « ANI », austérité, chômage, etc.), la bouse soudainement posée n’en a pas moins le mauvais goût de tomber au plus mauvais moment — il est bien vrai que le spectacle de la cupidité déboutonnée, lors même que le corps social en bave comme jamais, donne quelques envies de coups de fourche. Elle y ajoute surtout un effet de révélation potentiellement dévastateur si l’on en vient à considérer que les « péripéties », loin d’être des exceptions locales sans signification globale, sont en fait les expressions d’un système, et qu’il n’est peut-être pas fortuit qu’on retrouve identiquement cette passion de l’argent dans tous les gouvernements qui se succèdent pour garantir sa continuité à l’austérité ainsi qu’à toutes les politiques…";


$textes[29]["source"] = "https://blog.mondediplo.net/2012-11-21-Economistes-institutions-pouvoirs";
$textes[29]["txt"] = "Sur un sujet à haute teneur polémique comme celui d’aujourd’hui, il est peut-être utile de ne pas céder immédiatement à l’envie (pourtant fort légitime) de la castagne et, au moins au début, de maintenir quelques exigences analytiques, conceptuelles même. Pour commencer donc, et dût la chose vous surprendre, voici ce que dit la proposition 12 de la partie III de l’Éthique : « L’esprit s’efforce autant qu’il le peut d’imaginer ce qui augmente la puissance d’agir de son corps. » La chose ne vous paraîtra sans doute pas aller de soi à la première lecture, mais cette proposition livre ni plus ni moins que le principe de l’idéologie, à savoir que la pensée est gouvernée par des intérêts à penser, mais de toutes sortes bien sûr, très généralement les intérêts du conatus, c’est-à-dire tout ce qui peut lui être occasion de joie (c’est-à-dire d’augmentation de la puissance d’agir de son corps). Derrière la pensée donc il y a toujours des désirs particuliers de penser, déterminés bien sûr par les propriétés idiosyncratiques de l’individu pensant, mais aussi — et en fait…";


$textes[30]["source"] = "https://blog.mondediplo.net/2014-02-26-Les-entreprises-ne-creent-pas-l-emploi";
$textes[30]["txt"] = "Il faut avoir sérieusement forcé sur les boissons fermentées, et se trouver victime de leur propension à faire paraître toutes les routes sinueuses, pour voir, comme s’y emploie le commentariat quasi-unanime, un tournant néolibéral dans les annonces récentes de François Hollande. Sans porter trop hauts les standards de la sobriété, la vérité appelle plutôt une de ces formulations dont Jean-Pierre Raffarin nous avait enchantés en son temps : la route est droite et la pente est forte — mais très descendante (et les freins viennent de lâcher). En effet, droit, c’est droit ! Et depuis l’origine. Évidemment, pour s’en apercevoir, il aurait fallu prêter un peu plus attention aux six premiers mois de la présidence Hollande, où tout a été posé pour cinq ans, et les actes et la logique des actes. Ce texte est la version longue de l’article paru dans Le Monde diplomatique de mars 2014. Les actes d’abord, en une séquence impressionnante de cohérence : ambassade du premier ministre à l’université du MEDEF, reculade devant les « pigeons », rapport Gallois, consécration…";


$textes[31]["source"] = "https://blog.mondediplo.net/2017-09-18-Vivre-et-penser-comme-des-DRH";
$textes[31]["txt"] = "Tu parles ! C’est toute la classe macronienne qui en a d’avance le système glandulaire surmené. Car sous la pellicule fine des ultra-riches, du reste probablement indifférents à cette insane bouillie verbale, s’ils n’en rient pas eux aussi — mais autrement —, il y a toute la petite troupe électorale des wanabees qui, eux, s’y croient à fond. Ils lisent Challenges ou Winner comme jadis on lisait Salut les copains : avec des étoiles dans les yeux, se ruinent le poignet sur des posters dépliables de Xavier Niel, se repassent dans la voiture leurs leçons de globish, optimisent leurs process, ne rêvent que d’être « augmentés », vivent la vie comme une startup. On n’aurait pas d’obstacles à ce qu’ils restent entre eux, comme dans une sorte de parc à thème, qui par parenthèses pourrait connaître un réel succès, c’est qu’il y a des choses à voir et à entendre qui méritent qu’on paye. Le problème est que ces débiles ont la forme de vie agressivement envahissante, et qu’ils ont même pour projet d’y mettre tout le monde : ils se sont d’ailleurs donné un président pour ça.…";


$textes[32]["source"] = "https://fr.wikisource.org/wiki/Lettres_de_mon_moulin/Installation";
$textes[32]["txt"] = "Ce sont les lapins qui ont été étonnés… Depuis si longtemps qu’ils voyaient la porte du moulin fermée, les murs et la plate-forme envahis par les herbes, ils avaient fini par croire que la race des meuniers était éteinte, et, trouvant la place bonne, ils en avaient fait quelque chose comme un quartier général, un centre d’opérations stratégiques : le moulin de Jemmapes des lapins… La nuit de mon arrivée, il y en avait bien, sans mentir, une vingtaine assis en rond sur la plate-forme, en train de se chauffer les pattes à un rayon de lune… Le temps d’entrouvrir une lucarne, frrt ! voilà le bivouac en déroute, et tous ces petits derrières blancs qui détalent, la queue en l’air, dans le fourré. J’espère bien qu’ils reviendront. Quelqu’un de très étonné aussi, en me voyant, c’est le locataire du premier, un vieux hibou sinistre, à tête de penseur, qui habite le moulin depuis plus de vingt ans. Je l’ai trouvé dans la chambre du haut, immobile et droit sur l’arbre de couche, au milieu des plâtras, des tuiles tombées. Il m’a regardé un moment avec son œil rond ; Puis,…";


$textes[33]["source"] = "http://classiques.uqac.ca/contemporains/russell_bertrand/Eloge_oisivete/Eloge_oisivete_texte.html";
$textes[33]["txt"] = "Ainsi que la plupart des gens de ma génération, j’ai été élevé selon le principe que l’oisiveté est mère de tous vices. Comme j’étais un enfant pétri de vertu, je croyais tout ce qu’on me disait, et je me suis doté d’une conscience qui m’a contraint à peiner au travail toute ma vie. Cependant, si mes actions ont toujours été soumises à ma conscience, mes idées, en revanche, ont subi une révolution. En effet, j’en suis venu à penser que l’on travaille beaucoup trop de par le monde, que de voir dans le travail une vertu cause un tort immense, et qu’il importe à présent de faire valoir dans les pays industrialisés un point de vue qui diffère radicalement des préceptes traditionnels. Tout le monde connaît l’histoire du voyageur qui, à Naples, vit douze mendiants étendus au soleil (c’était avant Mussolini), et proposa une lire à celui qui se montrerait le plus paresseux. Onze d’entre eux bondirent pour venir la lui réclamer : il la donna donc au douzième. Ce voyageur était sur la bonne piste. Toutefois, dans les contrées qui ne bénéficient pas du soleil méditerranéen,…";


$textes[34]["source"] = "https://fr.wikisource.org/wiki/Le_Droit_à_la_paresse";
$textes[34]["txt"] = "Un poète grec du temps de Cicéron, Antiparos, chantait ainsi l’invention du moulin à eau (pour la mouture du grain) : il allait émanciper les femmes esclaves et ramener l’âge d’or : « Épargnez le bras qui fait tourner la meule, ô meunières, et dormez paisiblement ! Que le coq vous avertisse en vain qu’il fait jour ! Dao a imposé aux nymphes le travail des esclaves et les voilà qui sautillent allègrement sur la roue et voilà que l’essieu ébranlé roule avec ses raies, faisant tourner la pesante pierre roulante. Vivons de la vie de nos pères et oisifs réjouissons-nous des dons que la déesse accorde. » Hélas ! les loisirs que le poète païen annonçait ne sont pas venus : la passion aveugle, perverse et homicide du travail transforme la machine libératrice en instrument d’asservissement des hommes libres : sa productivité les appauvrit. Une bonne ouvrière ne fait avec le fuseau que cinq mailles à la minute, certains métiers circulaires à tricoter en font trente mille dans le même temps. Chaque minute à la machine équivaut donc à cent heures de travail de l’ouvrière :…";


$textes[35]["source"] = "https://fr.wikisource.org/wiki/Le_Droit_à_la_paresse";
$textes[35]["txt"] = "Si, en diminuant les heures de travail, on conquiert à la production sociale de nouvelles forces mécaniques, en obligeant les ouvriers à consommer leurs produits, on conquerra une immense armée de forces de travail. La bourgeoisie, déchargée alors de sa tâche de consommateur universel, s’empressera de licencier la cohue de soldats, de magistrats, de figaristes, de proxénètes, etc., qu’elle a retirée du travail utile pour l’aider à consommer et à gaspiller. C’est alors que le marché du travail sera débordant, c’est alors qu’il faudra une loi de fer pour mettre l’interdit sur le travail : il sera impossible de trouver de la besogne pour cette nuée de ci-devant improductifs, plus nombreux que les poux des bois. Et après eux il faudra songer à tous ceux qui pourvoyaient à leurs besoins et goûts futiles et dispendieux. Quand il n’y aura plus de laquais et de généraux à galonner, plus de prostituées libres et mariées à couvrir de dentelles, plus de canons à forer, plus de palais à bâtir, il faudra, par des lois sévères, imposer aux ouvrières et ouvriers en passementeries,…";


$textes[36]["source"] = "https://fr.wikisource.org/wiki/Le_Droit_à_la_paresse";
$textes[36]["txt"] = "Une étrange folie possède les classes ouvrières des nations où règne la civilisation capitaliste. Cette folie traîne à sa suite des misères individuelles et sociales qui, depuis des siècles, torturent la triste humanité. Cette folie est l’amour du travail, la passion moribonde du travail, poussée jusqu’à l’épuisement des forces vitales de l’individu et de sa progéniture. Au lieu de réagir contre cette aberration mentale, les prêtres, les économistes, les moralistes, ont sacro-sanctifié le travail. Hommes aveugles et bornés, ils ont voulu être plus sages que leur Dieu ; hommes faibles et méprisables, ils ont voulu réhabiliter ce que leur Dieu avait maudit. Moi, qui ne professe d’être chrétien, économe et moral, j’en appelle de leur jugement à celui de leur Dieu ; des prédications de leur morale religieuse, économique, libre penseuse, aux épouvantables conséquences du travail dans la société capitaliste. Dans la société capitaliste, le travail est la cause de toute dégénérescence intellectuelle, de toute déformation organique. Comparez le pur-sang des écuries de…";


$textes[37]["source"] = "https://wikilivres.org/wiki/Le_Petit_Prince";
$textes[37]["txt"] = "Les grandes personnes m’ont conseillé de laisser de côté les dessins de serpents boas ouverts ou fermés, et de m’intéresser plutôt à la géographie, à l’histoire, au calcul et à la grammaire. C’est ainsi que j’ai abandonné, à l’âge de six ans, une magnifique carrière de peintre. J’avais été découragé par l’insuccès de mon dessin numéro 1 et de mon dessin numéro 2. Les grandes personnes ne comprennent jamais rien toutes seules, et c’est fatigant, pour les enfants, de toujours leur donner des explications… J’ai donc dû choisir un autre métier et j’ai appris à piloter des avions. J’ai volé un peu partout dans le monde. Et la géographie, c’est exact, m’a beaucoup servi. Je savais reconnaître, du premier coup d’œil, la Chine de l’Arizona. C’est utile, si l’on s’est égaré pendant la nuit. J’ai ainsi eu, au cours de ma vie, des tas de contacts avec des tas de gens sérieux. J’ai beaucoup vécu chez les grandes personnes. Je les ai vues de très près. Ça n’a pas trop amélioré mon opinion. Quand j’en rencontrais une qui me paraissait un peu lucide, je faisais l’expérience…";


?>
